"""
heatmap_generator.py
--------------------
Generates an ATT&CK Navigator layer JSON from the attack chain.

The output file can be imported directly into:
  https://mitre-attack.github.io/attack-navigator/

Color coding:
  - Red   (#e03d3d) : rule-based high confidence (≥ 0.85)
  - Orange(#e07d00) : STIX / medium confidence   (≥ 0.65)
  - Yellow(#a0a000) : ML / low confidence        (< 0.65)
  - Gray  (#888888) : post-exploitation evidence
"""

import json
import datetime


def _confidence_to_color(confidence: float, source: str) -> str:
    if source == "post_exploit":
        return "#888888"
    if confidence >= 0.85:
        return "#e03d3d"
    if confidence >= 0.65:
        return "#e07d00"
    return "#a0a000"


class HeatmapGenerator:

    def generate(self, chain: dict, target: str = "target") -> dict:
        """
        Build the ATT&CK Navigator layer dict from the chain.
        """
        techniques_layer = []
        seen = set()

        for phase, data in chain.items():
            tactic = data.get("tactic", "")
            for tech in data.get("techniques", []):
                tid    = tech.get("id", "")
                conf   = tech.get("confidence", data.get("confidence", 0.5))
                source = tech.get("source", data.get("source", "unknown"))

                if not tid:
                    continue

                key = f"{tid}:{tactic}"
                if key in seen:
                    continue
                seen.add(key)

                techniques_layer.append({
                    "techniqueID": tid,
                    "tactic":      tactic.replace("-", " ") if tactic else None,
                    "score":       int(round(conf * 100)),
                    "color":       _confidence_to_color(conf, source),
                    "comment":     (
                        f"Phase {phase} | "
                        f"Source: {source} | "
                        f"Confidence: {conf:.2f} | "
                        f"Hosts: {', '.join(data.get('hosts', []))}"
                    ),
                    "enabled":     True,
                    "metadata":    [],
                    "showSubtechniques": False
                })

        # Remove None tactic entries (Navigator requires non-null or omission)
        for entry in techniques_layer:
            if entry["tactic"] is None:
                del entry["tactic"]

        layer = {
            "name":        f"Red Team Coverage — {target}",
            "versions":    {"attack": "14", "navigator": "4.9", "layer": "4.5"},
            "domain":      "enterprise-attack",
            "description": (
                f"Generated by Hybrid AI Penetration Testing Framework\n"
                f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
                f"Target: {target}"
            ),
            "filters": {
                "platforms": [
                    "Linux", "Windows", "macOS",
                    "Network", "PRE", "Containers"
                ]
            },
            "sorting":          3,
            "layout": {
                "layout":           "side",
                "aggregateFunction": "max",
                "showID":           True,
                "showName":         True,
                "showAggregateScores": True,
                "countUnscored":    False
            },
            "hideDisabled":     False,
            "techniques":       techniques_layer,
            "gradient": {
                "colors": ["#ffffff", "#e03d3d"],
                "minValue": 0,
                "maxValue": 100
            },
            "legendItems": [
                {"label": "Rule-based (high confidence)",  "color": "#e03d3d"},
                {"label": "STIX lookup (medium confidence)","color": "#e07d00"},
                {"label": "ML classifier (low confidence)", "color": "#a0a000"},
                {"label": "Post-exploitation evidence",     "color": "#888888"},
            ],
            "metadata":  [],
            "links":     [],
            "showTacticRowBackground": True,
            "tacticRowBackground": "#dddddd",
            "selectTechniquesAcrossTactics": False,
            "selectSubtechniquesWithParent": False,
        }

        return layer

    def save(self, layer: dict, filepath: str):
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(layer, f, indent=2, ensure_ascii=False)
        print(f"  [+] ATT&CK Navigator layer saved: {filepath}")
        print(f"  [+] Import at: https://mitre-attack.github.io/attack-navigator/")
