// ── Session ───────────────────────────────────────────
export const DEMO_SESSION = {
  session_id:     "SIM-A3F9",
  target:         "192.168.1.100",
  status:         "done",
  mode:           "dry-run",
  started_at:     "2026-05-17T11:38:00",
  progress:       100,
  current_module: "reporting",
  summary: {
    hosts_found:         1,
    total_vulnerabilities: 2,
    exploit_attempts:    2,
    successful_exploits: 1,
    rules_fired:         8,
    session_id:          "SIM-A3F9",
  },
};

// ── Hosts ─────────────────────────────────────────────
export const DEMO_HOSTS = [
  {
    ip_address: "192.168.1.100",
    hostname:   "metasploitable",
    os_type:    "LINUX",
    services: [
      { service_id: "192.168.1.100:21",   port_number: 21,   protocol: "tcp", service_name: "ftp",          product: "vsftpd",  version_string: "vsftpd 2.3.4" },
      { service_id: "192.168.1.100:22",   port_number: 22,   protocol: "tcp", service_name: "ssh",          product: "OpenSSH", version_string: "openssh 4.7"   },
      { service_id: "192.168.1.100:445",  port_number: 445,  protocol: "tcp", service_name: "microsoft-ds", product: "Samba",   version_string: "samba 3.0"     },
      { service_id: "192.168.1.100:80",   port_number: 80,   protocol: "tcp", service_name: "http",         product: "Apache",  version_string: "apache 2.2"    },
      { service_id: "192.168.1.100:3306", port_number: 3306, protocol: "tcp", service_name: "mysql",        product: "MySQL",   version_string: "mysql 5.0"     },
    ],
  },
];

// ── Vulnerabilities (from VULN_DB + _compute_risk_score) ─
export const DEMO_VULNS = [
  {
    cve_id:       "CVE-2011-2523",
    ip_address:   "192.168.1.100",
    service_name: "ftp",
    port_number:  21,
    cvss_score:   10.0,
    risk_score:   0.95,
    attack_type:  "remote",
    requires_auth: false,
    msf_module:   "exploit/unix/ftp/vsftpd_234_backdoor",
    description:  "vsftpd 2.3.4 backdoor — remote code execution",
  },
  {
    cve_id:       "CVE-2007-2447",
    ip_address:   "192.168.1.100",
    service_name: "smb",
    port_number:  445,
    cvss_score:   9.3,
    risk_score:   0.88,
    attack_type:  "remote",
    requires_auth: false,
    msf_module:   "exploit/multi/samba/usermap_script",
    description:  "Samba usermap_script RCE",
  },
  {
    cve_id:       "CVE-2017-7679",
    ip_address:   "192.168.1.100",
    service_name: "http",
    port_number:  80,
    cvss_score:   9.8,
    risk_score:   0.84,
    attack_type:  "remote",
    requires_auth: false,
    msf_module:   "exploit/multi/http/apache_mod_cgi_bash_env_exec",
    description:  "Apache mod_mime buffer overflow",
  },
  {
    cve_id:       "CVE-2008-0166",
    ip_address:   "192.168.1.100",
    service_name: "ssh",
    port_number:  22,
    cvss_score:   7.8,
    risk_score:   0.52,
    attack_type:  "brute-force",
    requires_auth: true,
    msf_module:   null,
    description:  "Debian OpenSSL weak key generation",
  },
  {
    cve_id:       "CVE-2009-2446",
    ip_address:   "192.168.1.100",
    service_name: "mysql",
    port_number:  3306,
    cvss_score:   8.5,
    risk_score:   0.61,
    attack_type:  "authenticated",
    requires_auth: true,
    msf_module:   "exploit/windows/mysql/mysql_mof",
    description:  "MySQL COM_FIELD_LIST RCE",
  },
];

// ── Exploit attempts ──────────────────────────────────
export const DEMO_EXPLOITS = [
  {
    attempt_id: "sim_001",
    ip_address: "192.168.1.100",
    cve_id:     "CVE-2011-2523",
    tool_used:  "metasploit",
    msf_module: "exploit/unix/ftp/vsftpd_234_backdoor",
    port_number: 21,
    result:     "SUCCESS",
    timestamp:  "2026-05-17T12:00:00",
  },
  {
    attempt_id: "sim_002",
    ip_address: "192.168.1.100",
    cve_id:     "CVE-2007-2447",
    tool_used:  "metasploit",
    msf_module: "exploit/multi/samba/usermap_script",
    port_number: 445,
    result:     "FAIL",
    timestamp:  "2026-05-17T12:01:30",
  },
];

// ── MITRE ATT&CK (from MITRE_TECHNIQUES in post_exploitation.py) ─
export const DEMO_MITRE = {
  total_techniques: 7,
  tactics_covered:  6,
  by_tactic: {
    "Initial Access":       [{ id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access",       detail: "CVE-2011-2523" }],
    "Privilege Escalation": [{ id: "T1068", name: "Exploitation for Privilege Escalation", tactic: "Privilege Escalation", detail: "getsystem" }],
    "Credential Access":    [{ id: "T1003", name: "OS Credential Dumping",            tactic: "Credential Access",    detail: "hashdump" }],
    "Persistence":          [{ id: "T1547", name: "Boot/Logon Autostart Execution",   tactic: "Persistence",          detail: "SSH key" }],
    "Discovery":            [{ id: "T1082", name: "System Information Discovery",     tactic: "Discovery",            detail: "sysinfo" }],
    "Lateral Movement":     [{ id: "T1021", name: "Remote Services",                  tactic: "Lateral Movement",     detail: "arp sweep" }],
    "Exfiltration":         [{ id: "T1041", name: "Exfiltration Over C2 Channel",     tactic: "Exfiltration",         detail: "" }],
  },
};

// ── Rule trace (ctx.rule_log) ─────────────────────────
export const DEMO_RULES = [
  { rule: "R0",  condition: "target is 192.168.1.100",               action: "run Nmap host discovery" },
  { rule: "R1",  condition: "1 live host found",                     action: "proceed to scanning & enumeration" },
  { rule: "R3",  condition: "3 open ports on 192.168.1.100",         action: "run service & OS fingerprinting" },
  { rule: "R4",  condition: "OS detected: LINUX on 192.168.1.100",   action: "run linux-specific enumeration scripts" },
  { rule: "R5",  condition: "web ports found: {80} on 192.168.1.100",action: "run web directory discovery" },
  { rule: "R6",  condition: "ftp vsftpd 2.3.4 on 192.168.1.100",    action: "CVE-2011-2523 → MSF: exploit/unix/ftp/vsftpd_234_backdoor" },
  { rule: "R6",  condition: "smb samba 3.0 on 192.168.1.100",        action: "CVE-2007-2447 → MSF: exploit/multi/samba/usermap_script" },
  { rule: "R7",  condition: "exploit available | risk=0.95",          action: "trigger safe exploitation via metasploit" },
  { rule: "R9",  condition: "shell established on 192.168.1.100",    action: "proceed to post-exploitation" },
  { rule: "R10", condition: "all phases complete",                    action: "generate detailed report — PDF + JSON" },
];

// ── Session logs ──────────────────────────────────────
export const DEMO_LOGS = [
  "███████████████████████████████████████████████████",
  "  Rule-Based Adaptive Red Teaming Orchestrator",
  "  UCAS University — Cyber Security Engineering 2026",
  "███████████████████████████████████████████████████",
  "  Session ID : SIM-A3F9",
  "  Target     : 192.168.1.100",
  "  Dry Run    : True",
  "",
  "=======================================================",
  "[MODULE 1] Reconnaissance — Host Discovery",
  "=======================================================",
  "  [*] Running: nmap -sn -PE -PS22,80,443,445 -PA80,443 --min-rate 300 192.168.1.100",
  "  [+] Host UP: 192.168.1.100 (metasploitable)",
  "  ✓ Found 1 live host(s): ['192.168.1.100']",
  "",
  "=======================================================",
  "[MODULE 2] Scanning & Enumeration",
  "=======================================================",
  "  [*] Scanning host: 192.168.1.100",
  "  [*] Running: nmap -sV -O -sC --open -T4 --min-rate 500 192.168.1.100",
  "  [+] Services on 192.168.1.100 (OS: LINUX):",
  "      21/tcp   ftp                 vsftpd 2.3.4",
  "      22/tcp   ssh                 openssh 4.7",
  "      445/tcp  microsoft-ds        samba 3.0",
  "      80/tcp   http                apache 2.2",
  "      3306/tcp mysql               mysql 5.0",
  "  [R5] Web ports detected: {80} — web discovery queued",
  "",
  "=======================================================",
  "[MODULE 3] Vulnerability Mapping + AI Risk Scoring",
  "=======================================================",
  "  [*] Mapping vulnerabilities for 192.168.1.100",
  "  [+] CVE-2011-2523 | CVSS: 10.0 | Risk: 0.95 | ftp:21",
  "  [+] CVE-2007-2447 | CVSS: 9.3  | Risk: 0.88 | smb:445",
  "  [+] CVE-2017-7679 | CVSS: 9.8  | Risk: 0.84 | http:80",
  "  [+] CVE-2009-2446 | CVSS: 8.5  | Risk: 0.61 | mysql:3306",
  "  [+] CVE-2008-0166 | CVSS: 7.8  | Risk: 0.52 | ssh:22",
  "",
  "=======================================================",
  "[MODULE 4] Exploitation",
  "=======================================================",
  "  [*] Targeting host: 192.168.1.100",
  "  [*] 5 vulnerability(ies) to try (sorted by risk)",
  "  [*] Metasploit: exploit/unix/ftp/vsftpd_234_backdoor → 192.168.1.100:21",
  "  ✓ EXPLOITATION SUCCESS — CVE-2011-2523 on 192.168.1.100",
  "",
  "=======================================================",
  "[MODULE 5] Post-Exploitation + MITRE ATT&CK Mapping",
  "=======================================================",
  "  [*] Post-exploitation on 192.168.1.100",
  "  [*] System discovery...",
  "  [+] System info collected",
  "  [*] Attempting privilege escalation...",
  "  [+] Privilege escalation: ROOT/SYSTEM obtained",
  "  [*] Harvesting credentials...",
  "  [+] Found 2 password hash(es)",
  "  [*] Establishing persistence...",
  "  [+] Persistence established",
  "  [+] Pivot candidates: ['192.168.1.101']",
  "  ✓ Post-exploitation complete for 192.168.1.100",
  "",
  "=======================================================",
  "[MODULE 6] Reporting (R10)",
  "=======================================================",
  "  ✓ JSON report : reports/report_SIM-A3F9.json",
  "  ✓ Text report : reports/report_SIM-A3F9.txt",
  "  ✓ PDF report  : reports/report_SIM-A3F9.pdf",
];
