"""
OWASP Report Builder - Generates professional security reports
Based on OWASP Top 10 2025 standards
Reference: https://github.com/OWASP/Top10
"""

import json
from datetime import datetime

class OWASPReportBuilder:
    def __init__(self):
        self.owasp_version = "Top 10 2025"
    
    def build_report(self, scan_results: dict, format: str = "html") -> str:
        if format == "html":
            return self._build_html(scan_results)
        return json.dumps(scan_results, indent=2)
    
    def _build_html(self, results: dict) -> str:
        filename = f"owasp_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        html = f"""<!DOCTYPE html>
<html>
<head><title>OWASP Security Report - OWASP Top 10 2025</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 20px; }}
.container {{ max-width: 1000px; margin: 0 auto; }}
h1 {{ color: #333; border-bottom: 3px solid #667eea; }}
.finding {{ margin: 15px 0; padding: 10px; background: #f9f9f9; border-left: 4px solid; }}
.critical {{ border-left-color: #d32f2f; }}
.high {{ border-left-color: #f44336; }}
.medium {{ border-left-color: #ff9800; }}
.footer {{ text-align: center; margin-top: 20px; font-size: 12px; color: #666; }}
</style>
</head>
<body>
<div class="container">
<h1>🔒 OWASP {self.owasp_version} Security Report</h1>
<p><strong>Target:</strong> {results.get('target', 'N/A')}</p>
<p><strong>Scan Time:</strong> {datetime.now()}</p>
<p><strong>Reference:</strong> <a href="https://github.com/OWASP/Top10">github.com/OWASP/Top10</a></p>
<h2>Findings ({len(results.get('vulnerabilities', []))})</h2>
"""
        for f in results.get('vulnerabilities', []):
            risk = f.get('risk', 'medium').lower()
            html += f'<div class="finding {risk}"><h3>{f.get("title")}</h3><p>{f.get("description")}</p><p><strong>Remediation:</strong> {f.get("remediation")}</p></div>'
        html += f'<div class="footer"><p>Generated by OWASP Security Scanner | Based on <a href="https://github.com/OWASP/Top10">OWASP Top 10 2025</a></p></div></div></body></html>'
        with open(filename, 'w') as f:
            f.write(html)
        return filename
